package org.gudmap.queries.solr;



public class SolrQueries {
	
	public final static String GET_INSITU_DATA = "SELECT COUNT(DISTINCT MBC_SUB_ACCESSION_ID) " +
			"FROM MIC_BROWSE_CACHE, ANA_TIMED_NODE, ANA_NODE " +
			"WHERE ATN_PUBLIC_ID = MBC_COMPONENT_ID " +
			"AND ATN_NODE_FK = ANO_OID ";
	
	


public final static String GET_TISSUE_DATA = "SELECT A.CSC_OID AS ID, A.CSC_DISPLAY_NAME AS NAME, A.CSC_SYNONYM AS SYNONYM, A.CSC_STAGES AS STAGES, REPLACE ( REPLACE ( REPLACE (" +
			"REPLACE ( REPLACE ( REPLACE(A.CSC_FOCUS_GROUP,'MET','metanephros'),'LUT','lower urinary tract'),'EGS','early genitourinary " +
			"system'),'MRS','male reproductive system'),'FRS','female reproductive system'),'UNK','unknown') AS FOCUS_GROUPS, GROUP_CONCAT(DISTINCT " +
			"CSN_GENELIST_ID_FK SEPARATOR ';') AS GENELIST_IDS, GROUP_CONCAT(DISTINCT GNL_SHORT_NAME SEPARATOR ';') AS GENELIST_NAMES," +
			"CSI_IMAGE_LOC_URL AS IMAGE_URL, CSI_IMAGE_NAME AS IMAGE_NAME, GROUP_CONCAT(DISTINCT B.CSC_DISPLAY_NAME SEPARATOR ';') AS SEC_NAMES," +
			"GROUP_CONCAT(DISTINCT CST_TYPE SEPARATOR ';') AS LINK_TYPES,SOLR_TS_EMAPIDS.TS_GUDMAP_IDS AS GUDMAP,REPLACE " +
			"(SOLR_TS_EMAPIDS.TS_EMAP_IDS,'EMAP:','') AS EMAP,SOLR_TS_EMAPIDS.TS_EMAP_IDS AS EMAPIDS,SOLR_TS_EMAPIDS.TS_COMP_NAMES AS " +
			"COMPONENT,REPLACE (SOLR_TS_EMAPIDS.TS_MGI_IDS,'MGI:','') AS MGI,SOLR_TS_EMAPIDS.TS_MGI_IDS AS GENE_MGI_ID,SOLR_TS_EMAPIDS.TS_GENE AS " +
			"GENE,SOLR_TS_EMAPIDS.TS_PROBE_IDS AS PROBE_IDS,SOLR_TS_EMAPIDS.TS_MAPROBES AS MA_PROBES_ID,REPLACE " +
			"(SOLR_TS_EMAPIDS.TS_MAPROBES,'maprobe:','') AS maprobe,SOLR_TS_EMAPIDS.TS_THEILER_STAGE AS THEILER_STAGE FROM CPS_COMPONENTS A LEFT JOIN " +
			"CPS_GENELIST_LINKS ON A.CSC_OID=CSN_CS_ID_FK LEFT JOIN REF_GENELISTS ON CSN_GENELIST_ID_FK=GNL_OID LEFT JOIN CPS_IMAGES ON " +
			"A.CSC_OID=CSI_CS_ID_FK LEFT JOIN CPS_LINKS ON A.CSC_OID=CSL_PRIMARY_ID LEFT JOIN CPS_LINK_TYPES ON CSL_LINK_TYPE=CST_OID LEFT JOIN " +
			"CPS_COMPONENTS B ON B.CSC_OID=CSL_SECONDARY_ID LEFT JOIN SOLR_TS_EMAPIDS ON A.CSC_OID=SOLR_TS_EMAPIDS.TS_ID WHERE A.CSC_VISIBLE=1 GROUP BY A.CSC_OID" ;

}