package org.gudmap.queries.disease;

public class DiseaseQueries {
	
	public DiseaseQueries() {
		
	}
	//LOOKUPS
	//SELECT DISEASE AND GENE
	//public static String PHENOTYPE_LIST = "SELECT PTY_TERM FROM DIS_PHENOTYPE ORDER BY PTY_TERM";
	public static String GENE_SYMBOLS = "SELECT DGA_SYMBOL, DGA_MGIACC FROM LNK_GENE_OMIMDIS WHERE (DGA_FLAG = 'N' || DGA_FLAG = 'U' || DGA_FLAG = 'R') GROUP BY DGA_SYMBOL";
	//public static String DISEASE_NAMES_2 = "SELECT OMD_NAME FROM DIS_OMIM_DISEASE, LNK_GENE_OMIMDIS where DGA_OMIMID = OMD_OMIMID and (DGA_FLAG = 'N' || DGA_FLAG = 'U') GROUP BY OMD_NAME ORDER BY OMD_NAME";
	public static String ALL_DISEASES = "SELECT count(*) AS DIS_COUNT FROM DIS_OMIM_DISEASE";
	public static String GENE_PTY_SYMBOLS = "SELECT DISTINCT GPY_SYMBOL FROM LNK_GENE_PTY";
	//PHENOTYPE
	public static String PHENOTYPE_LIST_2 = "SELECT PTY_TERM, PTY_MPID FROM DIS_PHENOTYPE ORDER BY PTY_TERM";
	public static String PHENOTYPE_ID_FROM_TERM = "SELECT PTY_MPID FROM DIS_PHENOTYPE WHERE PTY_TERM = ?";
	
	//RESULTS
	//DISEASE
	/*public static String GENES_ASSOC_DISEASE = "SELECT OMD_NAME, DGA_HSYMBOL, DGA_SYMBOL, DGA_MGIACC, OMD_OMIMID, DGA_EV_MYOMIM, DGA_FLAG, DGA_EV_NCBI " +
				"FROM LNK_GENE_OMIMDIS, DIS_OMIM_DISEASE WHERE DGA_OMIMID = OMD_OMIMID and OMD_NAME LIKE ? " +
				"AND (DGA_FLAG = 'N' || DGA_FLAG = 'U' || DGA_FLAG = 'R') ORDER BY DGA_SYMBOL, DGA_EV_MYOMIM";*/
	
	public static String GENES_ASSOC_DISEASE = "SELECT OMD_NAME disease_name, DGA_HSYMBOL human_gene_symbol, DGA_SYMBOL mouse_gene_symbol, DGA_MGIACC  mouse_gene_mgi_id, OMD_OMIMID omim_id, " +
			"DGA_EV_MYOMIM has_insitu_data, DGA_FLAG flag, DGA_EV_NCBI has_ncbi_data, '' mp_id, '' mp_phenotype, '' annotation_type " +
			"FROM LNK_GENE_OMIMDIS, DIS_OMIM_DISEASE WHERE DGA_OMIMID = OMD_OMIMID and OMD_NAME = ? " +
			"AND (DGA_FLAG = 'N' || DGA_FLAG = 'U' || DGA_FLAG = 'R') ORDER BY DGA_SYMBOL, DGA_EV_MYOMIM";
	
	//GENE
	//PARAM = "gene_text")
	/*public static String GENE_ASSOC_DISEASE_TERM = "SELECT OMD_NAME, DGA_HSYMBOL, DGA_SYMBOL, DGA_MGIACC, OMD_OMIMID, DGA_EV_MYOMIM, DGA_FLAG, DGA_EV_NCBI " +
				"FROM DIS_OMIM_DISEASE, LNK_GENE_OMIMDIS WHERE DGA_OMIMID = OMD_OMIMID and (DGA_FLAG = 'N' || DGA_FLAG = 'U' || DGA_FLAG = 'R') and DGA_SYMBOL = ?";*/
	
	public static String GENE_ASSOC_DISEASE_TERM = "SELECT OMD_NAME disease_name, DGA_HSYMBOL human_gene_symbol, DGA_SYMBOL mouse_gene_symbol, DGA_MGIACC mouse_gene_mgi_id, " +
			"OMD_OMIMID omim_id, DGA_EV_MYOMIM has_insitu_data, DGA_FLAG flag, DGA_EV_NCBI has_ncbi_data, '' mp_id, '' mp_phenotype, '' annotation_type " +
			"FROM DIS_OMIM_DISEASE, LNK_GENE_OMIMDIS WHERE DGA_OMIMID = OMD_OMIMID and (DGA_FLAG = 'N' || DGA_FLAG = 'U' || DGA_FLAG = 'R') and DGA_SYMBOL = ?";


	//if PARAM STARTS WITH "MGI:"
	/*public static String GENE_ASSOC_DISEASE_MGI = "SELECT OMD_NAME, DGA_HSYMBOL, DGA_SYMBOL, DGA_MGIACC, OMD_OMIMID, DGA_EV_MYOMIM, DGA_FLAG, DGA_EV_NCBI " +
				"FROM DIS_OMIM_DISEASE, LNK_GENE_OMIMDIS WHERE DGA_OMIMID = OMD_OMIMID and (DGA_FLAG = 'N' || DGA_FLAG = 'U' || DGA_FLAG = 'R') and DGA_MGIACC = ?";*/
	
	public static String GENE_ASSOC_DISEASE_MGI = "SELECT OMD_NAME disease_name, DGA_HSYMBOL human_gene_symbol, DGA_SYMBOL mouse_gene_symbol, DGA_MGIACC mouse_gene_mgi_id, " +
			"OMD_OMIMID omim_id, DGA_EV_MYOMIM has_insitu_data, DGA_FLAG flag, DGA_EV_NCBI has_ncbi_data, '' mp_id, '' mp_phenotype, '' annotation_type " +
			"FROM DIS_OMIM_DISEASE, LNK_GENE_OMIMDIS WHERE DGA_OMIMID = OMD_OMIMID and (DGA_FLAG = 'N' || DGA_FLAG = 'U' || DGA_FLAG = 'R') and DGA_MGIACC = ?";
	//PHENOTYPE 1
	/*public static String  GENES_ASSOC_PHENOTYPE= "SELECT DISTINCT GPY_GENE_MGIACC, RMM_SYMBOL, PTY_MPID, PTY_TERM FROM LNK_GENE_PTY, DIS_PTY_DERIVED, DIS_PHENOTYPE, " +
				"REF_MGI_MRK WHERE PDR_PARENT = ? AND (PDR_PARENT = GPY_MPID || PDR_CHILD = GPY_MPID) AND GPY_MPID = PTY_MPID AND GPY_GENE_MGIACC = RMM_MGIACC " +
				"AND GPY_DATA = 1 ORDER BY RMM_SYMBOL";*/
	
	public static String  GENES_ASSOC_PHENOTYPE= "SELECT DISTINCT '' disease_name,  '' human_gene_symbol, RMM_SYMBOL mouse_gene_symbol, GPY_GENE_MGIACC mouse_gene_mgi_id, " +
			"'' omim_id, '' has_insitu_data, '' flag, '' has_ncbi_data, PTY_MPID mp_id, PTY_TERM mp_phenotype, IF (PDR_TYPE = 'is','DIRECT','DERIVED')  annotation_type " +
			"FROM LNK_GENE_PTY, DIS_PTY_DERIVED, DIS_PHENOTYPE, " +
			"REF_MGI_MRK WHERE PDR_PARENT = ? AND (PDR_PARENT = GPY_MPID || PDR_CHILD = GPY_MPID) AND GPY_MPID = PTY_MPID AND GPY_GENE_MGIACC = RMM_MGIACC " +
			"AND GPY_DATA = 1 ORDER BY RMM_SYMBOL";
	
	//PHENOTYPE 2 (SEARCH BY GENE)
	public static String PHENOTYPE_BY_GENE = "SELECT DISTINCT PTY_MPID, PTY_TERM, RMM_SYMBOL, GPY_GENE_MGIACC " +
				"FROM LNK_GENE_PTY, DIS_PHENOTYPE, REF_MGI_MRK WHERE GPY_MPID=PTY_MPID AND GPY_GENE_MGIACC = RMM_MGIACC AND RMM_SYMBOL = ? ORDER BY PTY_MPID";
	
	/*public static String PHENOTYPE_BY_GENE_DIRECT = "SELECT DISTINCT PTY_MPID, PTY_TERM, RMM_SYMBOL, GPY_GENE_MGIACC, IF (PDR_TYPE = 'is','DIRECT','DERIVED') " +
				"FROM LNK_GENE_PTY, DIS_PHENOTYPE, DIS_PTY_DERIVED, REF_MGI_MRK WHERE GPY_MPID=PTY_MPID AND GPY_GENE_MGIACC = RMM_MGIACC AND PDR_PARENT = PDR_CHILD " +
				"AND RMM_SYMBOL = ? AND GPY_DATA =1 ORDER BY PTY_MPID";*/
	
	public static String PHENOTYPE_BY_GENE_DIRECT = "SELECT DISTINCT '' disease_name,  '' human_gene_symbol, RMM_SYMBOL mouse_gene_symbol, GPY_GENE_MGIACC mouse_gene_mgi_id, " +
			"'' omim_id, '' has_insitu_data, '' flag, '' has_ncbi_data, PTY_MPID mp_id, PTY_TERM mp_phenotype, IF (PDR_TYPE = 'is','DIRECT','DERIVED') annotation_type " +
			"FROM LNK_GENE_PTY, DIS_PHENOTYPE, DIS_PTY_DERIVED, REF_MGI_MRK WHERE GPY_MPID=PTY_MPID AND GPY_GENE_MGIACC = RMM_MGIACC AND PDR_PARENT = PDR_CHILD " +
			"AND RMM_SYMBOL = ? AND GPY_DATA =1 ORDER BY PTY_MPID";
	
	/*public static String PHENOTYPE_BY_GENE_DERIVED = "SELECT DISTINCT PTY_MPID, PTY_TERM, RMM_SYMBOL, GPY_GENE_MGIACC, IF (PDR_TYPE = 'is','DIRECT','DERIVED') " +
				"FROM DIS_PTY_DERIVED, DIS_PHENOTYPE, LNK_GENE_PTY, REF_MGI_MRK WHERE PDR_PARENT = PTY_MPID AND PDR_CHILD = GPY_MPID AND GPY_GENE_MGIACC = RMM_MGIACC " +
				"AND RMM_SYMBOL = ? AND GPY_DATA = 1 ORDER BY PTY_MPID";*/
	
	public static String PHENOTYPE_BY_GENE_DERIVED = "SELECT DISTINCT '' disease_name,  '' human_gene_symbol, RMM_SYMBOL mouse_gene_symbol, GPY_GENE_MGIACC mouse_gene_mgi_id, " +
			"'' omim_id, '' has_insitu_data, '' flag, '' has_ncbi_data, PTY_MPID mp_id, PTY_TERM mp_phenotype, IF (PDR_TYPE = 'is','DIRECT','DERIVED') annotation_type " +
			"FROM DIS_PTY_DERIVED, DIS_PHENOTYPE, LNK_GENE_PTY, REF_MGI_MRK WHERE PDR_PARENT = PTY_MPID AND PDR_CHILD = GPY_MPID AND GPY_GENE_MGIACC = RMM_MGIACC " +
			"AND RMM_SYMBOL = ? AND GPY_DATA = 1 ORDER BY PTY_MPID";
}
