package org.gudmap.queries.generic;

public class AutocompleteQueries {
	
	public static String GENE_SYMBOLS_AND_SYNONYMS = "(SELECT DISTINCT RPR_SYMBOL GENE FROM REF_PROBE " +
			"JOIN ISH_PROBE ON PRB_MAPROBE = RPR_OID " +
			"JOIN ISH_SUBMISSION ON PRB_SUBMISSION_FK = SUB_OID " +
			"WHERE RPR_SYMBOL <> '' " +
			"AND SUB_IS_PUBLIC = 1 AND SUB_IS_DELETED = 0 AND SUB_DB_STATUS_FK = 4 " +
			"AND (SUB_ASSAY_TYPE = 'ISH' OR SUB_ASSAY_TYPE = 'IHC' OR SUB_ASSAY_TYPE = 'TG') ) " +
			//"AND RPR_SYMBOL LIKE ?) " + // 1
			"UNION " +
			"(SELECT DISTINCT RSY_SYNONYM GENE FROM REF_SYNONYM " +
			"JOIN REF_MGI_MRK ON RSY_REF = RMM_ID " +
			"JOIN REF_PROBE ON RMM_SYMBOL = RPR_SYMBOL " +
			"JOIN ISH_PROBE ON PRB_MAPROBE = RPR_OID " +
			"JOIN ISH_SUBMISSION ON PRB_SUBMISSION_FK = SUB_OID " +
			"WHERE RSY_SYNONYM <> '' " +
			"AND SUB_IS_PUBLIC = 1 AND SUB_IS_DELETED = 0 AND SUB_DB_STATUS_FK = 4 " +
			"AND (SUB_ASSAY_TYPE = 'ISH' OR SUB_ASSAY_TYPE = 'IHC' OR SUB_ASSAY_TYPE = 'TG') ) " +
			//"AND RSY_SYNONYM LIKE ?) " + // 2
			"UNION " +
			"(SELECT DISTINCT GNF_SYMBOL GENE " +
			"FROM REF_GENE_INFO )" + //WHERE GNF_SYMBOL LIKE ?) " + // 3
			"UNION " +
			"(SELECT DISTINCT RSY_SYNONYM GENE FROM REF_SYNONYM " +
			"JOIN REF_MGI_MRK ON RSY_REF = RMM_ID " +
			"JOIN REF_GENE_INFO ON RMM_SYMBOL = GNF_SYMBOL ) " +// WHERE RSY_SYNONYM LIKE ?) " + // 4
			"ORDER BY NATURAL_SORT(GENE) ";// +
			//"LIMIT ? "; // 5
	
	public static String GENE_SYMBOLS_AND_SYNONYMS2 = "SELECT DISTINCT RPR_SYMBOL GENE FROM REF_PROBE " +
			"JOIN ISH_PROBE ON PRB_MAPROBE = RPR_OID " +
			"JOIN ISH_SUBMISSION ON PRB_SUBMISSION_FK = SUB_OID " +
			"WHERE RPR_SYMBOL <> '' " +
			"AND SUB_IS_PUBLIC = 1 AND SUB_IS_DELETED = 0 AND SUB_DB_STATUS_FK = 4 " +
			"AND (SUB_ASSAY_TYPE = 'ISH' OR SUB_ASSAY_TYPE = 'IHC' OR SUB_ASSAY_TYPE = 'TG') ORDER BY NATURAL_SORT(GENE) ";

}
