/*
 Advanced Tooltips
 Version: 1.1.0
 (c) 2013 DMXzone.com
 @build 04-12-2013 13:17:51
*/
(function(c){var e,h;function A(a){window.console&&window.console.log("[dmxTooltip] ",a)}function B(){window.tooltip&&window.tooltip.DMXTooltipHideTimeout&&(window.clearTimeout(window.tooltip.DMXTooltipHideTimeout),window.tooltip.DMXTooltipHideTimeout=null)}function C(){window.tooltip&&window.tooltip.DMXTooltipShowTimeout&&(window.clearTimeout(window.tooltip.DMXTooltipShowTimeout),window.tooltip.DMXTooltipShowTimeout=null)}function x(){return 6==n?'<iframe class="bgiframe" frameborder="0" tabindex="-1" src="javascript:false;" style="display:block;position:absolute;z-index:-1;top:expression(((parseInt(this.parentNode.currentStyle.borderTopWidth)||3)*-1)+\'px\');left:expression(((parseInt(this.parentNode.currentStyle.borderLeftWidth)||1)*-1)+\'px\');width:expression(this.parentNode.offsetWidth+\'px\');height:expression(this.parentNode.offsetHeight+\'px\');"/>':
""}function H(){var a;a='<div class="dmxtooltip" style="visibility:hidden">'+x();return a+'<div class="dmxtooltipcontent"></div></div>'}function o(){var a="styles";"string"==typeof window.stylesFolderName&&(a=window.stylesFolderName);var c=v.replace(/JS_Sources/,a);return c=c.replace(/ScriptLibrary/,a+"/dmxTooltips")}function q(d){return a.contentType?"image"==a.contentType:RegExp("^[a-z_\\+%,\\s\\-\\/\\.0-9:]+\\.(jpg|jpeg|gif|png)"+D+"$","i").test(d)}function E(){function d(b){if(g[b])return"auto"==
a.h&&c(".dmxtooltip .dmxtooltipcontent").css({height:"auto"}),'<img class="tooltipImage" src="'+b+'" />';g[b]=new Image;g[b].onload=function(){"auto"==a.h&&c(".dmxtooltip .dmxtooltipcontent").css({height:"auto"});c(".dmxtooltip .dmxtooltipcontent").html('<img src="'+b+'" style="display:none"/>').find("> img").fadeIn("fast");p(window.tooltip.target)};g[b].onerror=function(){0<c(".dmxtooltip .dmxtooltipcontent .tooltipImage").length&&c(".dmxtooltip").css({width:"auto",height:"auto",opacity:1}).find(".dmxtooltipcontent").html('<span style="font-family:Arial, Verdana, sans-serif;font-size:12px;">The image "'+
b+'" was not found!</span>');try{delete g[b]}catch(a){g[b]=null}};g[b].src=b;return'<div style="margin-top:'+(a.h&&"auto"!=a.h?a.h/2-8+"px":"auto")+';font-family:Arial, Verdana, sans-serif;font-size:12px;white-space:nowrap;overflow:hidden;"><img src="'+o()+'indicator_mozilla_blu.gif" align="absmiddle" class="tooltipImage" /> Loading image...</div>'}function j(b){b='<iframe frameborder="0" seamless="true" tabindex="-1" src="'+b+'" title="'+b+'" allowtransparency="true"';a.w&&(b+=' width="'+a.w+'"');
a.h&&(b+=' height="'+a.h+'"');return b+" />"}function b(a){var b=a.jquery?a:c(a);if(0===b.length)return String(a);b[0].parentNode&&(b=b.clone());return c("<span/>").append(b.css({visibility:"inherit"})).html()}function u(a){return c("<span/>").html(a).html()}var f=a.dataProvider,i="";switch((a.contentType||typeof f).toLowerCase()){case "text":i=c("<span/>").text(f).html();break;case "html":i=u(f);break;case "url":i=j(f);break;case "image":i=d(f);break;case "jquery":i=b(f);break;case "function":var i=
"",e=null;"function"==typeof f?e=f:"string"==typeof f&&"function"==typeof window[f]&&(e=window[f]);if(e)try{i=e()}catch(h){A(h)}i=u(i);break;case "string":i=q(f)?d(f):(RegExp("\\s","g").test(f)?0:/^(http:\/\/|\.\/|\.\.\/|\/)[^\s]+/i.test(f)||RegExp("^([a-z_\\+%,\\-\\/0-9:]+\\.[a-z0-9]+"+D+")$","i").test(f))?j(f):/[<>]/.test(f)?u(f):/^#\w/.test(f)?b(f):c("<span/>").text(f).html();break;case "object":f.constructor==Array?i=f.join(""):f.jquery&&(i=b(f));break;default:i=f.toString()}return i}function p(d){if(!d||
!d.target&&!d.nodeName&&!d==window)A("function setTooltipPosition called with invalid argument.");else{var j=c(window.tooltip),d=d.target&&!d.nodeName?d.target:d.handle?d.handle:d,d=c(d==window?"body":d),b=j.outerWidth(),g=j.outerHeight(),f=/left|mouse/i.test(a.showAt)?"none"==a.styleTheme?0:11:0,i=/right|mouse/i.test(a.showAt)?"none"==a.styleTheme?0:11:0,y=/bottom|mouse/i.test(a.showAt)?"none"==a.styleTheme?0:14:0,l=/top|mouse/i.test(a.showAt)?"none"==a.styleTheme?0:11:0;if("mouse"!=a.showAt)var r=
d.outerWidth(),s=d.outerHeight(),k=d.offset().left,m=d.offset().top;switch(a.showAt){case "xy":e=a.y;h=a.x;break;case "topleft":e=m-g;h=k-f;break;case "topright":e=m-g;h=k+r+i-b;break;case "top":e=m-g;h=k+Math.round(r/2-b/2);break;case "bottomleft":e=m+s;h=k-f;break;case "bottomright":e=m+s;h=k+r+i-b;break;case "bottom":e=m+s;h=k+Math.round(r/2-b/2);break;case "left":e=m+Math.round(s/2)-Math.round(g/2);h=k-b;break;case "lefttop":e=m-l;h=k-b;break;case "leftbottom":e=m+s+y-g;h=k-b;break;case "right":e=
m+Math.round(s/2)-Math.round(g/2);h=k+r;break;case "righttop":e=m-l;h=k+r;break;case "rightbottom":e=m+s+y-g;h=k+r;break;case "center":e=Math.round(m+s/2-g/2);h=k+Math.round(r/2)-Math.round(b/2);break;case "mouse":e=t.y+Math.max(a.mouseOffsetY,20)-l,h=t.x+Math.max(a.mouseOffsetX,10)-f}if("in"==a.showDirection)switch(a.showAt){case "bottomleft":case "bottomright":case "bottom":e=e-g+y;break;case "topleft":case "topright":case "top":e+=g-l;break;case "left":case "lefttop":case "leftbottom":h=h+b-f;
break;case "right":case "righttop":case "rightbottom":h=h-b+i+f}j.css({top:Math.round("cursor"==a.y?t.y+Math.max(a.mouseOffsetY,20)-l:isNaN(e)?a.y:e)+"px",left:Math.round("cursor"==a.x?t.x+Math.max(a.mouseOffsetX,10)-f:isNaN(h)?a.x:h)+"px"})}}for(var n,z=3,F=document.createElement("div"),I=F.getElementsByTagName("i");F.innerHTML="<\!--[if gt IE "+ ++z+"]><i></i><![endif]--\>",I[0];);n=4<z?z:void 0;var J=function(a){var c=a;if(n)switch(a.toString()){case "easeInBack":case "easeInOutBack":c="easeOutBack";
break;case "easeInElastic":case "easeInOutElastic":c="easeOutElastic"}return c},w={normal:function(d,j,b,e){if(q(a.dataProvider)&&g[a.dataProvider].complete)g[a.dataProvider].onload();p(d);c(this).css({opacity:1});"function"==typeof e&&window.setTimeout(function(){e.call(d)},2)},fade:function(d,j,b,e){if(q(a.dataProvider)&&g[a.dataProvider].complete)g[a.dataProvider].onload();p(d);c(this).animate({opacity:1},j,b,e)},slide:function(d,j,b,e){p(d);var f={opacity:1,width:0,height:0},i,h;q(a.dataProvider)&&
g[a.dataProvider]?(i="auto"==a.w?g[a.dataProvider].width+46:c(this).outerWidth(),h="auto"==a.h?g[a.dataProvider].height+58:c(this).outerHeight()):(i=c(this).outerWidth(),h=c(this).outerHeight());var l={opacity:1,width:i+"px",height:h+"px"};q(a.dataProvider)?"auto"==a.w||"auto"==a.h?(h=i=0,c(this).css(l),p(d),window.tooltipSlideHelper||(window.tooltipSlideHelper=function(d,f){d||(d=0);f||(f=0);if(g[a.dataProvider])if(f>750)g[a.dataProvider].onerror();else{f++;d=Math.min(d+0.01,1);c(window.tooltip).css({width:++i,
height:++h,opacity:d});if(!g[a.dataProvider].width||!g[a.dataProvider].height)window.setTimeout("window.tooltipSlideHelper("+d+", "+f+")",40);else{g[a.dataProvider].onload();var k={opacity:1,width:g[a.dataProvider].width+46,height:g[a.dataProvider].height+58};c(window.tooltip).animate(k,j,b,e)}}}),window.tooltipSlideHelper(1)):(p(d),g[a.dataProvider].onload(),c(this).css(f).animate(l,j,b,e)):c(this).css(f).animate(l,j,b,e)},slideandfade:function(d,j,b,e){p(d);var f={opacity:0,width:0,height:0},i,
h;q(a.dataProvider)&&g[a.dataProvider]?(i="auto"==a.w?g[a.dataProvider].width+46:c(this).outerWidth(),h="auto"==a.h?g[a.dataProvider].height+58:c(this).outerHeight()):(i=c(this).outerWidth(),h=c(this).outerHeight());var l={opacity:1,width:i,height:h};q(a.dataProvider)?"auto"==a.w||"auto"==a.h?(h=i=0,c(this).css(l),window.tooltipSlideHelper||(window.tooltipSlideHelper=function(d,f){d||(d=0);f||(f=0);if(g[a.dataProvider])if(f>750)g[a.dataProvider].onerror();else{f++;d=Math.min(d+0.01,1);c(window.tooltip).css({width:++i,
height:++h,opacity:d});if(!g[a.dataProvider].width||g[a.dataProvider].height)window.setTimeout("window.tooltipSlideHelper("+d+", "+f+")",40);else{var k={opacity:1,width:g[a.dataProvider].width+46,height:g[a.dataProvider].height+58};g[a.dataProvider].onload();c(window.tooltip).animate(k,j,b,e)}}}),window.tooltipSlideHelper()):(p(d),g[a.dataProvider].onload(),c(this).css(f).animate(l,j,b,e)):c(this).css(f).animate(l,j,b,e)},fly:function(d,j,b,u){if(q(a.dataProvider)&&g[a.dataProvider].complete)g[a.dataProvider].onload();
var f={top:e,left:h};p(d);d={top:e,left:h,opacity:1};c(this).css(f).animate(d,j,b,u)}};window.tooltip=null;var a={},t={x:0,y:0};e=h=0;var v="",G={none:{haspointers:!1},black:{haspointers:!0},blue:{haspointers:!0},bluebevel:{haspointers:!0},darkgreybevel:{haspointers:!0},grey:{haspointers:!0},greybevel:{haspointers:!0},red:{haspointers:!0},redbevel:{haspointers:!0},transparentblack:{haspointers:!0},transparentgrey:{haspointers:!0},transparentwhite:{haspointers:!0},white:{haspointers:!0},yellow:{haspointers:!0},
yellowbevel:{haspointers:!0}},D="[\\?&;=-\\|\\\\/_a-z0-9\\+%]*",g={};c(function(){var a=v=c("script[src$='dmxTooltips.js']").attr("src").replace(/dmxTooltips\.js$/,""),a=String(a),a=jQuery('<a href="'+a+'" />');v=String(String(a[0].href));var a=[{file:"jquery.easing.1.3.js",type:"js"},{file:"structure.css",type:"css"},{file:"pointers.css",type:"css"}],e;for(e in a)"css"==a[e].type?c("head link[href$='"+a[e].file+"']").length||c("head").append('<link rel="stylesheet" type="text/css" href="'+o()+a[e].file+
'" />'):"js"==a[e].type&&(c("head script[src$='"+a[e].file+"']").length||c("head").append('<script type="text/javascript" language="javascript" src="'+v+a[e].file+'"><\/script>'));n&&(e='<style type="text/css">.dmxtooltiptable .tl,     .dmxtooltiptable .t ,          .dmxtooltiptable .tr,.dmxtooltiptable .l ,     .dmxtooltiptable .r ,          .dmxtooltiptable .bl,.dmxtooltiptable .b ,     .dmxtooltiptable .br,          .dmxtooltiptable .tl,.dmxtooltiptable .left,   .dmxtooltiptable .leftbottom,  .dmxtooltiptable .lefttop,.dmxtooltiptable .top,    .dmxtooltiptable .topleft,     .dmxtooltiptable .topright, .dmxtooltiptable .bottom, .dmxtooltiptable .bottomleft,  .dmxtooltiptable .bottomright, .dmxtooltiptable .right,  .dmxtooltiptable .rightbottom, .dmxtooltiptable .righttop { filter:progid:DXImageTransform.Microsoft.AlphaImageLoader();',
6==n&&(e+="behavior:url("+o()+"png.htc);"),c("head").append(e+"}<style>"));var a=["closebtn_faded.gif","closebtn.gif"],b="tl.png t.png tr.png l.png r.png bl.png b.png br.png".split(" "),h=c("html").html();e=[].concat(["indicator_mozilla_blu.gif","closebtn_faded.png","closebtn.png"]);6==n&&e.concat(a);for(var f in G)if("none"!=f&&RegExp("applyDMXTooltip\\s*\\([^\\)]+'"+f+"'","g").exec(h))for(a=0;a<b.length;a++)e.push(f+"/"+b[a]);f=o();for(a=0;a<e.length;a++)b=f+""+e[a],g[b]=new Image,g[b].src=b;window.tooltip=
c("body").prepend(H()).find(".dmxtooltip")[0];window.tooltip.target=null;c(n?document:window).bind("mousemove.tooltipNew",function(a){t.x=a.pageX;t.y=a.pageY});c(window.tooltip).bind("click.tooltip",function(a){a.stopPropagation()});window.setInterval(function(){window.tooltip.target||c(window.tooltip).css({visibility:"hidden"})},1E3);c(window.tooltip).bind("mouseenter.tooltip",function(){B()})});c(window).bind("unload",function(){delete g});window.hideDmxTooltip=function(){c(window.tooltip).css({visibility:"hidden"})[0].target=
null;c(window.tooltip)[0].animated=!1};window.showTooltip=function(d,e){B();if(window.tooltip&&window.tooltip.target&&window.tooltip.target==d)return!1;c(d).unbind("mouseleave.tooltip");c(d).unbind("mousemove.tooltip");c(window.tooltip).unbind("mouseleave.tooltip");c("body").unbind("click.tooltip");c(window.tooltip).css({visibility:"hidden"});window.tooltip.target=d;C();c(window.tooltip).stop();c(window.tooltip)[0].animated=!1;window.tooltip.DMXTooltipShowTimeout=window.setTimeout(function(){d||(d=
c("body")[0]);d.jquery&&(d.selector&&(d=c(d.selector)),0===d.length&&(d=c("body")),d=d[0]);"string"==typeof d&&(d=c(d),0===d.length&&(d=c("body")),d=d[0]);if(!d)return!1;var b=e,b=b||{};a.dataProvider=b.dataProvider||"Empty tooltip";a.contentType=b.contentType||null;a.showEffect=b.showEffect?"function"==typeof w[b.showEffect]?b.showEffect:"normal":"normal";a.showDuration=b.showDuration||0===b.showDuration?/^slow|normal|fast$/.test(b.showDuration.toString())?b.showDuration.toString():isNaN(parseInt(b.showDuration,
10))?400:Math.max(parseInt(b.showDuration,10),1):400;a.showDelay=b.showDelay?isNaN(parseInt(b.showDelay,10))?600:Math.max(parseInt(b.showDelay,10),1):600;a.moveWithCursor="undefined"!=typeof b.moveWithCursor?!1===b.moveWithCursor?!1:!0===b.moveWithCursor?!0:!1:!1;a.mouseOffsetX=b.mouseOffsetX?!isNaN(parseInt(b.mouseOffsetX,10))?Math.max(parseInt(b.mouseOffsetX,10),10):10:10;a.mouseOffsetY=b.mouseOffsetY?!isNaN(parseInt(b.mouseOffsetY,10))?Math.max(b.mouseOffsetY,20):20:20;a.onshow="function"==typeof a.onshow?
a.onshow:null;a.onhide="function"==typeof a.onhide?a.onhide:null;a.showDirection=b.showDirection?/^in|out$/.test(b.showDirection.toString())?b.showDirection.toString():"out":"out";a.styleTheme=b.styleTheme?G[b.styleTheme.toString()]?b.styleTheme.toString():"white":"white";a.easing=b.easing?jQuery.easing[b.easing.toString()]?b.easing.toString():"easeOutQuad":"easeOutQuad";a.showCloseBtn="undefined"!=typeof b.showCloseBtn?!1===b.showCloseBtn?!1:!0===b.showCloseBtn?!0:!1:!1;a.closeEvent=b.closeEvent?
/^mouseout|clickout|never$/.test(b.closeEvent.toString())?b.closeEvent.toString():"mouseout":"mouseout";a.showAt=b.showAt?/^bottomleft|bottomright|bottom|topleft|topright|top|left|lefttop|leftbottom|right|righttop|rightbottom|center|mouse|xy$/.test(b.showAt.toString())?b.showAt.toString():"bottomleft":"bottomleft";a.x=b.x?isNaN(parseInt(b.x,10))?/auto|cursor/i.test(b.x.toString())?b.x:0:parseInt(b.x,10):0;a.y=b.y?isNaN(parseInt(b.y,10))?/auto|cursor/i.test(b.y.toString())?b.y:0:parseInt(b.y,10):0;
a.w=b.w?isNaN(parseInt(b.w,10))?"auto"==b.w?b.w:0:parseInt(b.w,10):0;a.h=b.h?isNaN(parseInt(b.h,10))?"auto"==b.h?b.h:0:parseInt(b.h,10):0;b="";"none"!=a.styleTheme?(c('link[href$="/'+a.styleTheme+'.css"]').length||c("head").append('<link rel="stylesheet" type="text/css" href="'+o()+a.styleTheme+"/"+a.styleTheme+'.css" />'),a.showCloseBtn&&6==n&&(b+='<a href="javascript:void(0);" onclick="hideDmxTooltip()" class="ieclosebtn"><img src="'+o()+'closebtn_faded.gif" border="0" onmouseover="this.src = \''+
o()+"closebtn.gif';\"  onmouseout=\"this.src = '"+o()+'closebtn_faded.gif\';" title="Close" alt="Close" width="9" height="9" /></a>'),b+='<table cellspacing="0" cellpadding="0" border="0" class="'+a.styleTheme+' dmxtooltiptable">',b=n?b+('<tbody class="IE'+(6==n?" ie6":"")+'">'):b+"<tbody>",b+=' <tr>  <td class="tl">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>  <td class="t">'+("out"==a.showDirection?'<div class="'+a.showAt+'">&nbsp;</div>':"&nbsp;")+'</td>  <td class="tr" align="left" valign="bottom">',a.showCloseBtn&&
6!=n&&(b+='<a href="javascript:void(0);" onclick="hideDmxTooltip()" style="line-height:11px;text-align:left;"><img src="'+o()+'closebtn_faded.png" border="0" onmouseover="this.src = \''+o()+"closebtn.png';\"  onmouseout=\"this.src = '"+o()+'closebtn_faded.png\';" title="Close" alt="" align="left" vspace="0" style="left:0px;width:9px;height:9px;line-height:9px;" /></a>'),b+='</td> </tr> <tr>  <td class="l"'+("out"==a.showDirection?a.showAt.match(/top$/)?' valign="top"':a.showAt.match(/bottom$/)?' valign="bottom"':
' valign="middle"':"")+">"+("out"==a.showDirection?'<div class="'+a.showAt+'">&nbsp;</div>':"&nbsp;")+"</td>",b+='  <td class="c"',a.w&&"auto"!=a.w&&(b+=' width="'+a.w+'"'),a.h&&"auto"!=a.h&&(b+=' height="'+a.h+'"'),b+='>   <div class="dmxtooltipcontent" style="width:'+(a.w&&"auto"!=a.w?a.w+"px":"auto")+";height:"+(a.h&&"auto"!=a.h?a.h+"px":"100%")+';overflow:auto;"></div>  </td>  <td class="r"'+("out"==a.showDirection?a.showAt.match(/top$/)?' valign="top"':a.showAt.match(/bottom$/)?' valign="bottom"':
' valign="middle"':"")+">"+("out"==a.showDirection?'<div class="'+a.showAt+'">&nbsp;</div>':"&nbsp;")+'</td> </tr> <tr>  <td class="bl">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>  <td class="b">'+("out"==a.showDirection?'<div class="'+a.showAt+'">&nbsp;</div>':"&nbsp;")+'</td>  <td class="br">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr></tbody></table>',c(".dmxtooltip").html(x()+b).find(".dmxtooltipcontent").html(E())):c(".dmxtooltip").html(x()+'<div class="dmxtooltipcontent">'+E()+"</div>");switch(a.closeEvent){case "clickout":c("body").bind("click.tooltip",
function(){c(window.tooltip.target).unbind("mousemove.tooltip");c(window.tooltip).css({visibility:"hidden"})[0].target=null;c(window.tooltip)[0].animated=false});break;case "closebtn":break;case "never":break;default:c(window.tooltip).bind("mouseleave.tooltip",function(a){if(!window.tooltip.target||(a.toElement||a.relatedTarget)==this.target)return true;window.tooltip.DMXTooltipHideTimeout=window.setTimeout(function(){c(window.tooltip.target).unbind("mousemove.tooltip");window.tooltip.target=null},
500)}),c(d).bind("mouseleave.tooltip",function(a){if(jQuery.inArray(a.toElement||a.relatedTarget,c(".dmxtooltip, .dmxtooltip *").add(c(this)))<0){C();window.tooltip.DMXTooltipHideTimeout=window.setTimeout(function(){c(window.tooltip.target).unbind("mousemove.tooltip");window.tooltip.target=null},500)}else window.tooltip.target=d})}b="function"==typeof w[a.showEffect]?w[a.showEffect]:w.normal;"fly"!=a.showEffect&&("cursor"==a.y||"cursor"==a.x)&&c(d).bind("mousemove.tooltip",function(){p(d)});c(window.tooltip).css({visibility:"visible",
opacity:0,width:"auto",height:"auto"})[0].animated=!0;b.call(window.tooltip,d,RegExp("^(normal|fast|slow)$","gi").test(a.showDuration.toString())?a.showDuration:parseInt(a.showDuration,10),J(a.easing),function(){c(window.tooltip)[0].animated=false;typeof a.onshow=="function"&&a.onshow.call(window.tooltip);a.showEffect=="fly"&&(a.y=="cursor"||a.x=="cursor")&&c(d).bind("mousemove.tooltip",function(){p(d)});if(n>6)c(".dmxtooltip")[0].style.cssText=c(".dmxtooltip")[0].style.cssText.replace(/\bfilter\s*:[^;]*;/gi,
"")})},e.showDelay||0===e.showDelay?isNaN(e.showDelay)?600:Math.max(parseInt(e.showDelay,10),1):600)};c.fn.dmxTooltip=function(a){window.showTooltip(c(this)[0],a||{})}})(jQuery);
